# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roost < Formula
  desc "Recap any past Claude Code session in 50ms"
  homepage "https://github.com/Thomaspeel6/roost"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Thomaspeel6/roost/releases/download/v0.2.0/roost_0.2.0_darwin_amd64.tar.gz"
      sha256 "0562633d22dce9fb3bbf9556a1d2b76db415ea5f693b5030e36e87225e48d37e"

      define_method(:install) do
        bin.install "roost"
        bin.install "roost-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Thomaspeel6/roost/releases/download/v0.2.0/roost_0.2.0_darwin_arm64.tar.gz"
      sha256 "c07cad3d48ac9af103450f68e30e31c08deeb6708d2362b998f9533ee997f7f7"

      define_method(:install) do
        bin.install "roost"
        bin.install "roost-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thomaspeel6/roost/releases/download/v0.2.0/roost_0.2.0_linux_amd64.tar.gz"
      sha256 "abe7ea31676ef7018c6ab73fdd4ead39fe7afa4f98cf5da10292c97f3da71625"
      define_method(:install) do
        bin.install "roost"
        bin.install "roost-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thomaspeel6/roost/releases/download/v0.2.0/roost_0.2.0_linux_arm64.tar.gz"
      sha256 "e0f19a80589e31017cd41bb2c12432f2084e7664c780da0af860fd75dec2fdf1"
      define_method(:install) do
        bin.install "roost"
        bin.install "roost-hook"
      end
    end
  end

  test do
    system "#{bin}/roost", "version"
  end
end
